# Generated by Django 5.1.7 on 2025-03-13 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='ebook_available',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='physical_book_available',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
