# Generated by Django 5.1.7 on 2025-03-13 09:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_physicalbookinventory_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicalbookinventory',
            name='author',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='books.author'),
        ),
        migrations.AlterField(
            model_name='physicalbookinventory',
            name='location',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
