# Generated by Django 5.1.7 on 2025-03-13 09:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_alter_physicalbookinventory_author_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BookUserRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Returned', 'returned'), ('Not Returned', 'not returned')], max_length=50)),
                ('borrowing_date', models.DateField()),
                ('supposed_returning_date', models.DateField()),
                ('returned_date', models.DateField()),
                ('fine', models.PositiveIntegerField()),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.physicalbook')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.bookuser')),
            ],
        ),
    ]
